### ISSUE TITLE
z-index with IR headers

### ISSUE THREAD

**Issue by maxime-tremblay** [Pretius/apex-date-range#1]
The IR headers are showing above the daterange picker:
![2016-12-22 09-39-12](https://cloud.githubusercontent.com/assets/15253364/21429087/463eb51c-c82b-11e6-9ce2-27dbd499d24b.png)

The z-index of the IR is set to 300, so you could fix it by updating the CSS to:
```
.daterangepicker {
  position: absolute;
  color: #393939;
  background: #fff;
  border-radius: 2px;
  display: none;
  /*width: 278px;*/
  padding: 8px;
  margin-top: 1px;
  top: -100%;
  left: -100%;
  z-index: 400;  /*add this line*/
}
```

**Comment by ma-schroeder** [comment]
Hi,
i use "Left Side Column" as site template and the daterange pickers are in the "Left Column". Here the z-index of 400 is still not enough as the popup is displayed behind the left column:

![image](https://cloud.githubusercontent.com/assets/11662301/21615067/2f9f58e2-d1dc-11e6-8a43-5e9a70529368.png)

I changed it to 500 and this worked:

![image](https://cloud.githubusercontent.com/assets/11662301/21615139/72818bc6-d1dc-11e6-903e-34c42fe9b40d.png)

**Comment by bostrowski** [comment]
Thank you for your contribution @maxime-tremblay and @ma-schroeder. I will be releasing bug fixes this week.

**Comment by bostrowski** [comment]
z-index 700 is default since 1.1.0
