### ISSUE TITLE
Calendar dates have wrong weekday

### ISSUE THREAD

**Issue by ma-schroeder** [Pretius/apex-date-range#2]
Hi,

the calendar seems to be off by one day. The 01.01.2017 is a Sunday but in your calendar its a Monday. Today is Tuesday the 03.01. and in the demo it is shown as a Wednesday. See:

![image](https://cloud.githubusercontent.com/assets/11662301/21614837/70bb0d72-d1db-11e6-84d0-9931f3a4a10d.png)

**Comment by bostrowski** [comment]
Thank you @ma-schroeder. I will give it a look.

**Comment by bostrowski** [comment]
@ma-schroeder 
Ok, I have found the root of this evil behaviour ;-). I will add fix to planned release v1.1 (this week).

If you need to fix it ASAP you have to edit the plugin PL/SQL in **Shared components > Plugins > Pretius APEX Date Range** section **Source**. Replace line `111`

`  lang_app_days_of_week       varchar2(200)  := getTranslation('PRETIUS_DATERANGEPICKER_DAYS'         , 'Mo,Tu,We,Th,Fr,Sa,Su');`

with

`  lang_app_days_of_week       varchar2(200)  := getTranslation('PRETIUS_DATERANGEPICKER_DAYS'         , 'Su,Mo,Tu,We,Th,Fr,Sa');`

After saving, the plugin will display days names in correct correlation with day number in month

**Comment by ma-schroeder** [comment]
Thanks, this is working. But i had to set "First Day" to 2 in Component Settings:

![image](https://cloud.githubusercontent.com/assets/11662301/21634673/368a963a-d259-11e6-968f-883b84d5ad1c.png)

![image](https://cloud.githubusercontent.com/assets/11662301/21634682/42fc0926-d259-11e6-9667-f9ddfee2e88f.png)

**Comment by bostrowski** [comment]
its default since 1.2.0
