### ISSUE TITLE
Warn on Unsaved Changes is not being respected

### ISSUE THREAD

**Issue by martindsouza** [Pretius/apex-date-range#4]
When setting the page item option: `Warn on Unsaved Changes` to `Ignore`, the plugin doesn't look at this option.

When compared to a basic text page item, when the value is set to `ignore` the page item has `js-ignoreChange` added to the class. 

Not sure if there's a supported API for this or need to query the page item attributes to find the option setting then manually add the class.

**Comment by bostrowski** [comment]
@martindsouza 
I will investigate it. Thanks.

**Comment by bostrowski** [comment]
it is supported since 1.2.0.
