### ISSUE TITLE
Date-Range Single Field Syntax

### ISSUE THREAD

**Issue by DavidFerrol** [Pretius/apex-date-range#9]
Hi, can anyone help me regarding the syntax involved in exposing the to/from values from a single-field. 

I'd like to use the to/from values as part of my BETWEEN clause in my PL/SQL query.
I understand that the two value are separated by " - ", but I am unable to extract the values before and after the " - ".
I tried this <code>to_date(SUBSTR(:P2_DATERANGE, 1 ,INSTR(:P2_DATERANGE, ' - ', 1, 1)-1),'DD-MON-YY')</code> (for example) to extract the first value, but it doesn't seem to be working.

Any help would be greatly appreciated.

**Comment by bostrowski** [comment]
@DavidFerrol 

If it is for filtering then you can inspect this SQL Query which I've testes on **emp** table:
```sql
with test as (
  select 
    to_date(substr('1981-04-02 - 1981-06-09', 1, instr('1981-04-02 - 1981-06-09', ' - ')), 'YYYY-MM-DD') date_start,
    to_date(substr('1981-04-02 - 1981-06-09', instr('1981-04-02 - 1981-06-09', ' - ')+3), 'YYYY-MM-DD') date_end
  from 
    dual
)
select
  emp.*
from
  emp, 
  test
where
  hiredate between date_start and date_end
```

which results in showing rows according to given range of dates:

![image](https://user-images.githubusercontent.com/15342508/68317704-dfb09f00-00bb-11ea-9b40-9e62bf583c10.png)

**Comment by DavidFerrol** [comment]
I think I forgot to say thanks! 🤭
This was a great help and fixed my problem.

Sorry for the late reply and thanks for this solution.
